---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./adguard
  - ./calico
  - ./cloudflare-dns/ks.yaml
  - ./metallb/ks.yaml
  - ./traefik/ks.yaml
  - ./traefik-crds
